name: Hugo

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ pre-content-move ]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      HUGO_VERSION: "0.133.1"
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb 

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: Europe/Madrid
        run: |
          hugo \
            --gc \
            --minify 

      - name: Sync
        # https://stackoverflow.com/questions/54503807/how-to-access-the-value-of-secrets-in-github-actions
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          ls -la deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            ./public/ "${{secrets.DEST}}"
          rm deploy_key