name: Hugo publish

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: # This exposes the CID output of the action to the rest of the workflow
      cid: ${{ steps.deploy.outputs.cid }}
    env:
      HUGO_VERSION: "0.147.2"
    steps:
      - name: Install Hugo and w3cli
        id: setup
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb \
          && npm install -g @web3-storage/w3cli 

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build Hugo site for web server
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: Europe/Madrid
        run: |
          hugo \
            --gc \
            --minify 

      - name: Sync
        # https://stackoverflow.com/questions/54503807/how-to-access-the-value-of-secrets-in-github-actions
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          ls -la deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            ./public/ "${{secrets.DEST}}"
          rm deploy_key

      - name: Build Hugo site for IPFS
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: ipfs
          TZ: Europe/Madrid
        run: |
          hugo \
            --gc \
            --minify 

      - name: Deploy to IPFS
        uses: ipfs/ipfs-deploy-action@v1
        id: deploy
        with:
          path-to-deploy: public # Change this to your build output directory
          storacha-key: ${{ secrets.STORACHA_KEY }}
          storacha-proof: ${{ secrets.STORACHA_PROOF }}
          github-token: ${{ github.token }}
          set-github-status: true

      - name: Add IPFS header
        # https://stackoverflow.com/questions/54503807/how-to-access-the-value-of-secrets-in-github-actions
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          ls -la deploy_key
          chmod 600 ./deploy_key
          echo Header set x-ipfs-path "/ipfs/${{ steps.deploy.outputs.cid }}" >> ./public/.htaccess
          rsync -chav \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            ./public/.htaccess "${{secrets.DEST}}"
          rm deploy_key          
